# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-iam-policy
  description: Create an IAM policy from Terraform input
  homepage: https://cloudposse.com/accelerate
  topics: ""


